#!/bin/bash
# gums-host wrapper
#

BINDIR=$(dirname $0)
DEBUG=0
#
# Quotes all arguments with spaces in them, like DNs 
#
ARGS=""

for arg ; do 
	case $arg in
		
		--gumsdebug)
		DEBUG=1
		echo "[DEBUG] gums-host: Setting debug." 1>&2	
		ARGS="$ARGS $arg"
		;;
	
		*)
		origlen=${#arg}
		nospace=${arg//' '/''}
		newlen=${#nospace}
		if [ $newlen -lt $origlen ]; then
			ARGS="$ARGS \"$arg\""
		else
			ARGS="$ARGS $arg"
		fi
		;;
		
	esac
	if [ $DEBUG -eq 1 ] ; then
		echo "[DEBUG] gums-host: Arg is $arg" 1>&2
		echo "[DEBUG] gums-host: ARGS are: $ARGS" 1>&2
	fi 
done 
eval $BINDIR/gums --host "$ARGS"