#!/bin/sh

# Detects where gums is installed and puts the directory
# name in ScriptPath

ScriptPath=""
CommandPath=`dirname $0`
if [ $CommandPath = "." ]
then

    # The command path is the current directory:
    # check if file is really here

    if [ ! -e "$0" ]
    then
        # The command is not in the current directory:
        # must have used the path.
        # Locating with which.

        WhichFull=`which $0`
        WhichPath=`dirname $WhichFull`
        ScriptPath=$WhichPath
        GumsPath=`dirname $ScriptPath`
    else
        # It was really the current directory
        ScriptPath=$CommandPath
        GumsPath=".."
    fi
else
    ScriptPath=$CommandPath
    GumsPath=`dirname $ScriptPath`
fi

# Detects where gums is installed and puts the directory
# name in ScriptPath

cd $ScriptPath
cd ../lib
LSLIB=`/bin/ls ../lib`
LIBCLASSPATH=`/bin/echo $LSLIB | /bin/sed -e 's/ /:/g'`
CLASSPATH=../config:$LIBCLASSPATH

ENDORSED="../lib/endorsed"

# defaults for the security code
CERTDIR=${X509_CERT_DIR-/etc/grid-security/certificates}

CERT=/etc/grid-security/hostcert.pem
KEY=/etc/grid-security/hostkey.pem

SECURITY_OPTS="-Daxis.socketSecureFactory=org.glite.security.trustmanager.axis.AXISSocketFactory 
-DsslCAFiles=$CERTDIR/*.0 -DsslCertFile=$CERT -DsslKey=$KEY"

java -Djava.endorsed.dirs=$ENDORSED $SECURITY_OPTS -cp ../config:$CLASSPATH gov.bnl.gums.admin.HostCommandLine "$@"
RETURN=$?
chmod 600 ../var/log/*`whoami`*
exit $RETURN
