#!/bin/bash
# gums-host wrapper
#
# Minor edit to test subversion hooks --jrh
# Second edit to test hooks --jrh
# Third edit to test hooks --jrh
# Fourth edit to test hooks --jrh
# Fifth edit to test hooks --jrh
# Sixth edit to test hooks --jrh
# Seventh edit to test hooks --jrh
# Eighth edit to test hooks --jrh
# Ningth edit to test hooks --jrh
BINDIR=$(dirname $0)
DEBUG=0
#
# Quotes all arguments with spaces in them, like DNs 
#
ARGS=""

for arg ; do 
	case $arg in
		
		--gumsdebug)
		DEBUG=1
		echo "[DEBUG] gums-host: Setting debug."
		ARGS="$ARGS $arg"
		;;
	
		*)
		origlen=${#arg}
		nospace=${arg//' '/''}
		newlen=${#nospace}
		if [ $newlen -lt $origlen ]; then
			ARGS="$ARGS \"$arg\""
		else
			ARGS="$ARGS $arg"
		fi
		;;
		
	esac
	if [ $DEBUG -eq 1 ] ; then
		echo "[DEBUG] gums-host: Arg is $arg"
		echo "[DEBUG] gums-host: ARGS are: $ARGS"
	fi 
done 
eval $BINDIR/gums --host "$ARGS"