#!/bin/bash
# gums-service wrapper
# 

BINDIR=$(dirname $0)#
# Quotes all arguments with spaces in them, like DNs 
#
for arg in "$@"; do 
	origlen=${#arg}
	nospace=${arg//' '/''}
	newlen=${#nospace}
	if [ $newlen -lt $origlen ]; then
		ARGS="$ARGS \"$arg\""
	else
		ARGS="$ARGS $arg"
	fi
done 
eval $BINDIR/gums --service $ARGS