#!/bin/sh

if [ "$1" == "" ]
then
  echo Adds an admin in the GUMS database on localhost
  echo "Usage: $0 [DN for administrator]"
  echo
  echo Example:
  echo   $0 \"/DC=org/DC=doegrids/OU=People/CN=Gabriele Carcassi 12345\"
  exit -1
fi


MYSQLPARAM="-u gums -p"
ADMINDN=$1

echo WARNING: You must have created the database before running this script!
echo
echo Adding the following DN to the local database:
echo Certificate DN for administrator: \"$ADMINDN\"
echo
echo "Is this correct? (Enter 'yes' to proceed)"

read response
if [ "$response" != "yes" ]
then
  exit -1
fi


echo
echo Adding the admin:
echo Enter the gums mysql password
echo "/usr/lib/gums/sql/addAdmin.mysql | sed -e "s%@ADMINDN@%$ADMINDN%g" | mysql $MYSQLPARAM"
cat /usr/lib/gums/sql/addAdmin.mysql | sed -e "s%@ADMINDN@%$ADMINDN%g" | mysql $MYSQLPARAM
echo

