#!/bin/sh

# Detects where gums is installed and puts the directory
# name in ScriptPath. Then cd to that directory.

ScriptPath=""
CommandPath=`dirname $0`
if [ $CommandPath = "." ]
then

    # The command path is the current directory:
    # check if file is really here

    if [ ! -e "$0" ]
    then
        # The command is not in the current directory:
        # must have used the path.
        # Locating with which.

        WhichFull=`which $0`
        WhichPath=`dirname $WhichFull`
        ScriptPath=$WhichPath
    else
        # It was really the current directory
        ScriptPath=$CommandPath
    fi
else
    ScriptPath=$CommandPath
fi

cd $ScriptPath


if [ "$1" == "" ]
then
  echo Adds an admin in the GUMS database on localhost
  echo "Usage: $0 [DN for administrator]"
  echo
  echo Example:
  echo   $0 \"/DC=org/DC=doegrids/OU=People/CN=Gabriele Carcassi 12345\"
  exit -1
fi


MYSQLPARAM="-u gums -p"
ADMINDN=$1

echo WARNING: You must have created the database before running this script!
echo
echo Adding the following DN to the local database:
echo Certificate DN for administrator: \"$ADMINDN\"
echo
echo "Is this correct? (Enter 'yes' to proceed)"

read response
if [ "$response" != "yes" ]
then
  exit -1
fi


echo
echo Adding the admin:
echo Enter the gums mysql password
echo ../sql/addAdmin.mysql pipe sed -e "s%@ADMINDN@%$ADMINDN%g" pipe mysql $MYSQLPARAM
cat ../sql/addAdmin.mysql | sed -e "s%@ADMINDN@%$ADMINDN%g" | mysql $MYSQLPARAM
echo

